// <auto-generated />
using System;
using BookStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221104173248_addedPrice")]
    partial class addedPrice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookStore.Model.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 2,
                            DateOfBirth = new DateTime(1992, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amir",
                            LastName = "Shakur"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            DateOfBirth = new DateTime(1962, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alli",
                            LastName = "Rulby"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 5,
                            DateOfBirth = new DateTime(1990, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hobbs",
                            LastName = "Tru"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            DateOfBirth = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            LastName = "Davids"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 3,
                            DateOfBirth = new DateTime(1964, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dan",
                            LastName = "Sinns"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 8,
                            DateOfBirth = new DateTime(1996, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Connel",
                            LastName = "MonRoe"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 5,
                            DateOfBirth = new DateTime(1990, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ruth",
                            LastName = "Pennylop"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 4,
                            DateOfBirth = new DateTime(1985, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Akin",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 1,
                            DateOfBirth = new DateTime(1980, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jenkins",
                            LastName = "snyder"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 7,
                            DateOfBirth = new DateTime(1991, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Avila",
                            LastName = "Lawren"
                        });
                });

            modelBuilder.Entity("BookStore.Model.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<bool>("BestSeller")
                        .HasColumnType("bit");

                    b.Property<int>("BookGenre")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            BestSeller = true,
                            BookGenre = 2,
                            Price = 60,
                            ReleaseDate = new DateTime(2002, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Heroes of Dawn"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            BestSeller = true,
                            BookGenre = 0,
                            Price = 65,
                            ReleaseDate = new DateTime(2010, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Goal With Money"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            BestSeller = false,
                            BookGenre = 1,
                            Price = 90,
                            ReleaseDate = new DateTime(1999, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blacksmiths And Butcher"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            BestSeller = true,
                            BookGenre = 2,
                            Price = 55,
                            ReleaseDate = new DateTime(2007, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Altering The West"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            BestSeller = false,
                            BookGenre = 0,
                            Price = 75,
                            ReleaseDate = new DateTime(2013, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inventing The Void"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            BestSeller = false,
                            BookGenre = 1,
                            Price = 65,
                            ReleaseDate = new DateTime(2006, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Traitor of The Banish"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 8,
                            BestSeller = true,
                            BookGenre = 0,
                            Price = 65,
                            ReleaseDate = new DateTime(2003, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Crossbow of Ashwas"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            BestSeller = false,
                            BookGenre = 2,
                            Price = 85,
                            ReleaseDate = new DateTime(2000, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Heroes of America"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            BestSeller = true,
                            BookGenre = 0,
                            Price = 115,
                            ReleaseDate = new DateTime(2015, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dawn of Apes"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 7,
                            BestSeller = false,
                            BookGenre = 1,
                            Price = 65,
                            ReleaseDate = new DateTime(2017, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vampires Tale"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 7,
                            BestSeller = false,
                            BookGenre = 1,
                            Price = 45,
                            ReleaseDate = new DateTime(2017, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vampires Tale"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            BestSeller = true,
                            BookGenre = 2,
                            Price = 15,
                            ReleaseDate = new DateTime(2019, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "UnHoly Truth"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
